//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPDATA> EMPDATAs { get; set; }
        public virtual DbSet<DEPTDATA> DEPTDATAs { get; set; }
    
        public virtual int sp_InsertEmp(Nullable<int> eno, string en, string job, Nullable<int> mgr, Nullable<System.DateTime> hdate, Nullable<int> sal, Nullable<int> comm, Nullable<int> dno, ObjectParameter r)
        {
            var enoParameter = eno.HasValue ?
                new ObjectParameter("Eno", eno) :
                new ObjectParameter("Eno", typeof(int));
    
            var enParameter = en != null ?
                new ObjectParameter("En", en) :
                new ObjectParameter("En", typeof(string));
    
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            var mgrParameter = mgr.HasValue ?
                new ObjectParameter("Mgr", mgr) :
                new ObjectParameter("Mgr", typeof(int));
    
            var hdateParameter = hdate.HasValue ?
                new ObjectParameter("Hdate", hdate) :
                new ObjectParameter("Hdate", typeof(System.DateTime));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("Sal", sal) :
                new ObjectParameter("Sal", typeof(int));
    
            var commParameter = comm.HasValue ?
                new ObjectParameter("Comm", comm) :
                new ObjectParameter("Comm", typeof(int));
    
            var dnoParameter = dno.HasValue ?
                new ObjectParameter("Dno", dno) :
                new ObjectParameter("Dno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertEmp", enoParameter, enParameter, jobParameter, mgrParameter, hdateParameter, salParameter, commParameter, dnoParameter, r);
        }
    }
}
