//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class v5
    {
        public string orderid { get; set; }
        public string orderdesc { get; set; }
        public Nullable<int> totalcost { get; set; }
        public Nullable<int> disamt { get; set; }
    }
}
